### ISSUE TITLE
[ADD] Colors for inquire types

### ISSUE THREAD

**Issue by alancampora** [labs-js/turbo-commit#2]
We're using inquiere dependency for showing commit type list. It's necessary to insert colors for each type.

[ADD] green
[DEL]  grey
[MOD] blue
[FIX] red
[REF] orange
[BRK] white

**Comment by sfabrizio** [comment]
I'm thinking in a new way to assign the colors now that we have another tag. This is my idea:

[ADD] green
[FIX] yellow
[MOD] blue
[DEL] red
[REF] orange
[BRK] violet
[MRG] white

**Comment by sfabrizio** [comment]
this was close on #13 by @alancampora
