### ISSUE TITLE
[REF] Refactor module

### ISSUE THREAD

**Issue by alancampora** [labs-js/turbo-commit#20]
It's possible split every command in different files. There is an example in Commander docs -
https://github.com/tj/commander.js/#git-style-sub-commands 

We should do the same, to keep a well-organized project structure.

**Comment by sfabrizio** [comment]
Yes, I agree.. I'm going to take a look to it! I'll create a branch for do this litle refactor

**Comment by alancampora** [comment]
It's done, now it's possible to have separate files for each command.

**Comment by sfabrizio** [comment]
Hahaha nice try! Let me close it to me :p
