### ISSUE TITLE
[FIX] Turbo log is not applying the color in some cases. 

### ISSUE THREAD

**Issue by alancampora** [labs-js/turbo-commit#32]
Sometimes the commit is not coloured by the command. Check if the regex is working properly

**Comment by sfabrizio** [comment]
Here a Screenshot..
<img width="414" alt="screen shot 2016-09-08 at 1 40 04 pm" src="https://cloud.githubusercontent.com/assets/4541773/18358101/eb65290e-75c9-11e6-92a6-f5dd6d31d199.png">

**Comment by sfabrizio** [comment]
okey I found out why this is happening in one case.. when we have the same string msg.. and I fixed already.. Here an example: https://jsfiddle.net/bysamo/vcpugfq7/7/

But It's not fixing the bug yet.. I need to continue analyzing this case..

**Comment by sfabrizio** [comment]
uff finally done!
